### ISSUE TITLE
Invalid bitrate validation while encoding video

### ISSUE THREAD

**Issue by tinoue** [danopdev/TimeLapse#1]
Thank you for your code. The VideoEncoder is a nice sample for video encoding.

https://github.com/danopdev/TimeLapse/blob/8953b5e744c5950680f61f74c0b2d79e9afeef64/app/src/main/java/com/dan/timelapse/video/VideoEncoder.kt#L38

I guess Its return value should be `range.start`.

**Comment by danopdev** [comment]
You are totally right :)
You can propose a pool request if you want, or I can do it.
